version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./output:/app/output
    command: python app/src/scraper.py

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: pytest
    volumes:
      - .:/app
